

                <div class='form-group'>
                    <label for='name'>Име</label>
                    <input minlength='5' maxlength='15' type='name' class='form-control' id='name' name='name' aria-describedby='name' placeholder='Въведи потребителско име(между 5 и 30 символа)'>
                </div>

                <div class='form-group'>
                    <label for='password'>Парола</label>
                    <input minlength='5' maxlength='30' type='password' class='form-control' id='password' name='password' aria-describedby='password' placeholder='Въведи парола(между 5 и 30 символа)'>
                </div>

                <br>

                    <label for='file'>Снимка на профила</label>
                    <input type='file' class='btn-primary' id='file' name='file' aria-describedby='file'>

                <br>

                